require "remarkable/controller/helpers"
require "remarkable/controller/macros"
require "remarkable/controller/routes/route"
require "remarkable/controller/renders/renders"
require "remarkable/controller/assigns/assigns"
require "remarkable/controller/responds/responds"
